### ISSUE TITLE
Building java code fails during test phase

### ISSUE THREAD

**Issue by Zubnix** [ashleyj/aura#14]
Building with `gradlew build` fails with the following error:

:llvm:test
aura.llvm.TargetMachineTest > testEmitToFile FAILED
    java.lang.UnsatisfiedLinkError at TargetMachineTest.java:33
aura.llvm.TargetMachineTest > testAssemble FAILED
    java.lang.NoClassDefFoundError at TargetMachineTest.java:46
aura.llvm.ObjectFileTest > testReadSections FAILED
    java.lang.NoClassDefFoundError at ObjectFileTest.java:62
aura.llvm.ObjectFileTest > testLineNumberInfo FAILED
    java.lang.NoClassDefFoundError at ObjectFileTest.java:123
aura.llvm.ObjectFileTest > testLoadFromFile FAILED
    java.lang.NoClassDefFoundError at ObjectFileTest.java:42
aura.llvm.ModuleTest > testParseIRString FAILED
    java.lang.NoClassDefFoundError at ModuleTest.java:36
aura.llvm.TargetTest > testGetTargets FAILED
    java.lang.NoClassDefFoundError at TargetTest.java:34
aura.llvm.TargetTest > testLookupTarget FAILED
    java.lang.NoClassDefFoundError at TargetTest.java:60
aura.llvm.TargetTest > testGetTarget FAILED
    java.lang.NoClassDefFoundError at TargetTest.java:47
aura.llvm.TargetTest > testGetTargetsMap FAILED
    java.lang.NoClassDefFoundError at TargetTest.java:40
13 tests completed, 10 failed, 3 skipped
:llvm:test FAILED

I was able to work around it by disabling the gradle task `-x llvm:test` but ideally that should not be used.

**Comment by ashleyj** [comment]
This error is caused by a missing library libaura-llvm.so -- There was a step missing in the instructions.
I've pushed the lib into the repo, so if you do a `git pull` you can pick up the change. Feel free to compile it yourself, but the dependency count is quite high.

**Comment by Zubnix** [comment]
The library you added will probably fix it (will try it out asap), but ideally I'd like to compile it myself as well. Unfortunately the added step (building libauro-llvm.so) fails, see comment in #15 Are there any required dependencies or steps that are assumed?

**Comment by Zubnix** [comment]
bug caused by #15 and workaround provided, so closing this ticket.
